name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-telegram-bot:latest
    - name: Run the Docker Image
      run: docker run -p 5000:5000 --name my_telegram_bot -d my-telegram-bot:latest
    - name: Show the logs
      run: docker logs my_telegram_bot
    - name: Show docker container
      run: docker ps -a
    - name: Check curl
      run: curl -v http://localhost:5000
